"use client";
import { useEffect, useState } from "react";

type Status={memberCount:number;memberEmails:string[];legacyMemberCount:number;passCount:number;academicYear:string;expiresAt:number;brevoConfigured:boolean;podurConfigured:boolean;calisConfigured:boolean;walletConfigured:boolean};

export function DiscountSettings(){
  const[state,setState]=useState<Status|null>(null);const[brevoApiKey,setBrevoApiKey]=useState("");const[podurCode,setPodurCode]=useState("");const[calisCode,setCalisCode]=useState("");const[walletServiceAccount,setWalletServiceAccount]=useState("");const[memberEmails,setMemberEmails]=useState("");const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);
  useEffect(()=>{fetch("/api/admin/discounts",{cache:"no-store"}).then(r=>r.json()).then((data:Status)=>{setState(data);setMemberEmails(data.memberEmails.join("\n"))})},[]);
  async function submit(confirmMemberRemoval=false){return fetch("/api/admin/discounts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({brevoApiKey,podurCode,calisCode,walletServiceAccount,memberEmails,confirmMemberRemoval})})}
  async function save(event:React.FormEvent){
    event.preventDefault();setSaving(true);setMessage("");let response=await submit();let data=await response.json();
    if(response.status===409&&data.confirmationRequired){const confirmed=window.confirm(`${data.message}\n\nTheir stored names will be deleted and their Wallet passes will stop working. Continue?`);if(confirmed){response=await submit(true);data=await response.json()}else{setSaving(false);setMessage("No changes were made.");return}}
    setSaving(false);if(!response.ok){setMessage(data.error??"Could not save settings.");return}setState(data);setBrevoApiKey("");setPodurCode("");setCalisCode("");setWalletServiceAccount("");setMemberEmails(data.memberEmails.join("\n"));setMessage("Member access saved securely.");
  }
  return <section className="settings">
    <p className="eyebrow">Committee setup</p><h1 className="display">MEMBER<br/><span>ACCESS</span></h1><p className="intro">View and edit who can receive ULISOC member discounts and Wallet passes.</p>
    <div className="summary"><span className={state?.brevoConfigured?"ready":"missing"}>{state?.brevoConfigured?"✓ Brevo connected":"Brevo key needed"}</span><span className={state?.podurConfigured?"ready":"missing"}>{state?.podurConfigured?"✓ PODUR code saved":"PODUR code needed"}</span><span className={state?.calisConfigured?"ready":"missing"}>{state?.calisConfigured?"✓ Cali's code saved":"Cali's code needed"}</span><span className={state?.walletConfigured?"ready":"missing"}>{state?.walletConfigured?"✓ Google Wallet connected":"Wallet key needed"}</span><span>{state?.memberCount??0} member emails</span><span>{state?.passCount??0} Wallet passes</span></div>
    <form onSubmit={save}>
      <label>Brevo API key <small>{state?.brevoConfigured?"Already saved — leave blank to keep it":"Paste the API v3 key"}</small><input type="password" autoComplete="off" value={brevoApiKey} onChange={e=>setBrevoApiKey(e.target.value)}/></label>
      <label>PODUR discount code <small>{state?.podurConfigured?"Already saved — leave blank to keep it":"Only verified members will receive this"}</small><input type="password" autoComplete="off" value={podurCode} onChange={e=>setPodurCode(e.target.value)}/></label>
      <label>Cali&apos;s discount code <small>{state?.calisConfigured?"Already saved — leave blank to keep it":"Only verified members will receive this"}</small><input type="password" autoComplete="off" value={calisCode} onChange={e=>setCalisCode(e.target.value)}/></label>
      <label>Google Wallet service-account JSON <small>{state?.walletConfigured?"Already encrypted and saved — leave blank to keep it":"Open the downloaded .json file, copy everything and paste it here"}</small><textarea className="secret-json" rows={5} value={walletServiceAccount} onChange={e=>setWalletServiceAccount(e.target.value)} placeholder={'{\n  "type": "service_account",\n  ...\n}'}/></label>
      <label>Member email list <small>One address per line. Removing an address requires confirmation and revokes its Wallet pass.</small><textarea rows={14} value={memberEmails} onChange={e=>setMemberEmails(e.target.value)} placeholder={state?"No viewable addresses saved yet.":"Loading member list…"}/></label>
      {Boolean(state?.legacyMemberCount)&&<p className="legacy" role="note">{state?.legacyMemberCount} existing {state?.legacyMemberCount===1?"address is":"addresses are"} protected by the old one-way format and cannot be shown. Paste the complete current list above and save once to make every entry viewable and editable.</p>}
      <button disabled={saving||!state}>{saving?"Saving securely…":"Save member access →"}</button>{message&&<p className="message" role="status">{message}</p>}
    </form>
    <p className="privacy">Memberships and Wallet passes for {state?.academicYear??"the current academic year"} expire automatically at the end of 31 July. The list and credentials are only available through the committee portal and are encrypted before storage.</p>
    <style>{`.settings{width:min(900px,calc(100% - 32px));margin:auto;padding:45px 0 80px}.settings h1{font-size:clamp(68px,11vw,112px);line-height:.82;margin:14px 0 28px}.settings h1 span{color:#b3222d}.intro{color:#bbb;font-size:17px;max-width:600px}.summary{display:flex;flex-wrap:wrap;gap:10px;margin:30px 0}.summary span{border:1px solid #3a3030;padding:10px 13px;font-size:13px}.summary .ready{color:#b8d6ad}.summary .missing{color:#ff9ca0}form{border:1px solid var(--border);background:#100e0e;padding:26px;display:grid;gap:22px}label{display:grid;gap:8px;color:#ddd;font-weight:800}small{color:#8f8885;font-weight:400}input,textarea{width:100%;border:1px solid #3a3030;background:#090808;color:#fff;padding:14px;font:inherit;font-size:16px}textarea{resize:vertical;line-height:1.65}.secret-json{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:13px}.legacy{margin:0;border-left:4px solid #d6b777;background:#1d1710;color:#e7d6a8;padding:14px;line-height:1.5}form button{border:0;background:#b3222d;color:#fff;padding:17px;font-weight:900;text-transform:uppercase;cursor:pointer}form button:disabled{opacity:.55;cursor:not-allowed}.message{margin:0;color:#d6b777}.privacy{font-size:13px;color:#777;line-height:1.6;margin-top:18px}@media(max-width:650px){form{padding:20px}.settings{padding-top:25px}}`}</style>
  </section>;
}
