"use client";
import { useEffect, useState } from "react";
import { Check, Copy, LockKeyhole, Mail } from "lucide-react";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";

export function PodurVerification({partner="PODUR"}:{partner?:"PODUR"|"Cali's"}) {
  const[email,setEmail]=useState("");const[challengeId,setChallengeId]=useState("");const[code,setCode]=useState("");const[discountCode,setDiscountCode]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);const[copied,setCopied]=useState(false);const[resendIn,setResendIn]=useState(0);
  useEffect(()=>{if(resendIn<=0)return;const timer=window.setInterval(()=>setResendIn(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[resendIn]);
  async function sendCode(){setLoading(true);setMessage("");const response=await fetch("/api/discounts/request-code",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const data=await response.json();setLoading(false);if(!response.ok){setMessage(data.error??"Could not send a code.");return}setChallengeId(data.challengeId);setCode("");setResendIn(60);setMessage("Code sent. Check your inbox and junk folder — it may take a minute to arrive.")}
  async function requestCode(event:React.FormEvent){event.preventDefault();await sendCode()}
  async function verify(event:React.FormEvent){event.preventDefault();setLoading(true);setMessage("");const response=await fetch("/api/discounts/verify-code",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({challengeId,code,partner:partner==="Cali's"?"calis":"podur"})});const data=await response.json();setLoading(false);if(!response.ok){setMessage(data.error??"Could not verify the code.");return}setDiscountCode(data.discountCode)}
  async function copy(){await navigator.clipboard.writeText(discountCode);setCopied(true);setTimeout(()=>setCopied(false),1800)}
  if(discountCode)return <div className="unlock success"><div className="icon"><Check/></div><p className="unlock-label">Member verified</p><h3>Your {partner} code</h3><button className="code" onClick={copy}><strong>{discountCode}</strong><span>{copied?<><Check/> Copied</>:<><Copy/> Copy</>}</span></button><p>Use this code at checkout. Please keep it within the ISoc membership.</p><style jsx>{styles}</style></div>;
  return <div className="unlock"><div className="icon">{challengeId?<Mail/>:<LockKeyhole/>}</div><p className="unlock-label">Members only</p><h3>{challengeId?"Check your email":"Unlock the discount code"}</h3>{!challengeId?<form onSubmit={requestCode}><label>Member email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><button disabled={loading}>{loading?"Sending…":"Email me a code →"}</button></form>:<form onSubmit={verify}><label>Six-digit code</label><InputOTP maxLength={6} value={code} onChange={setCode} inputMode="numeric" containerClassName="otp"><InputOTPGroup>{[0,1,2,3,4,5].map(index=><InputOTPSlot key={index} index={index} className="otp-slot"/>)}</InputOTPGroup></InputOTP><button disabled={loading||code.length!==6}>{loading?"Checking…":"Reveal discount →"}</button><div className="email-actions"><button className="text-button" type="button" disabled={loading||resendIn>0} onClick={sendCode}>{resendIn>0?`Resend code in ${resendIn}s`:"Resend code"}</button><button className="text-button" type="button" onClick={()=>{setChallengeId("");setCode("");setMessage("");setResendIn(0)}}>Use a different email</button></div></form>}{message&&<p className="message" role="status">{message}</p>}<p className="fine">We only use your email to confirm it appears on the ISoc member list.</p><style jsx>{styles}</style></div>;
}
const styles=`.unlock{height:100%;min-height:620px;padding:50px;background:linear-gradient(145deg,#171414,#0c0b0b);display:flex;flex-direction:column;justify-content:center}.icon{width:48px;height:48px;border:1px solid #4b4140;border-radius:50%;display:grid;place-items:center;color:#d0c4bd;margin-bottom:22px}.icon :global(svg){width:21px}.unlock-label{text-transform:uppercase;letter-spacing:.16em;font-size:12px;font-weight:800;color:#c52028;margin:0 0 10px}.unlock h3{font-size:30px;margin:0 0 25px}.unlock form{display:grid;gap:14px}.unlock label{display:grid;gap:8px;color:#aaa;text-transform:uppercase;letter-spacing:.08em;font-size:12px;font-weight:800}.unlock input{width:100%;border:1px solid #433b39;background:#090808;color:#fff;padding:15px;font-size:16px}.unlock form>button{border:0;background:#c52028;color:white;min-height:50px;padding:0 18px;font-size:13px;font-weight:900;text-transform:uppercase;cursor:pointer}.unlock form>button:disabled{opacity:.55}.email-actions{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.unlock .text-button{border:0;min-height:auto;background:transparent;color:#aaa;text-transform:none;font-weight:700;text-align:left;padding:5px 0;cursor:pointer}.unlock .text-button:disabled{color:#666;cursor:not-allowed}.message{color:#d6b777;line-height:1.5;font-size:14px}.fine{color:#777;font-size:12px;line-height:1.5;margin:22px 0 0}.unlock :global(.otp){margin:2px 0 6px}.unlock :global(.otp-slot){width:46px;height:52px;background:#090808;border-color:#433b39;color:#fff;font-size:20px;border-radius:0}.success .icon{color:#9bc38e}.success h3{margin-bottom:14px}.success .code{width:100%;border:1px solid #4b4140;background:#090808;color:#fff;padding:18px;display:flex;align-items:center;justify-content:space-between;cursor:pointer}.success .code strong{font-size:25px;letter-spacing:.08em}.success .code span{display:flex;align-items:center;gap:6px;color:#aaa;font-size:13px}.success .code :global(svg){width:16px}.success>p:last-child{color:#999;line-height:1.5;font-size:13px;margin:26px 0 0}@media(max-width:720px){.unlock{min-height:470px;padding:32px 24px}.unlock :global(.otp-slot){width:42px}.email-actions{align-items:flex-start;flex-direction:column;gap:8px}}`;
